### ISSUE TITLE
Why 1.19.3 version was removed from CurseForge?

### ISSUE THREAD

**Issue by ghost** [Benjamin-Norton/MCGPT#10]
I'm using this mod in my modpack and because of that can't update it without removing this beatiful mod. Maybe there is a way to put it back on curseforge?

**Comment by Bawnorton** [comment]
I removed 1.19.3 because it was using an older system that had since been deprecated and would've stopped working at some point in the very near future. I can back-port the current version to 1.19.3 but I won't be continuing with adding features to 1.19.3 as I will only be focusing on the most recent update as It is not feasible for me to maintain multiple versions of the same mod.

**Comment by ghost** [comment]
It would be really great if you'll make the backport. I think it's totally ok if it will not get updates. For now there is too small amount of mods ported to 1.19.4 so people with 1.19.3 packs will not be able to use your mod for really long time. Wish you best luck in your works!

**Comment by Bawnorton** [comment]
I don't have the time at the moment to work on back-porting so I've unarchived the latest version in 1.19.3. This version may break at some point in the near future.

**Comment by ghost** [comment]
Thank you very much. Wish you best luck!
