### ISSUE TITLE
Fine tune a model on startup 

### ISSUE THREAD

**Issue by adam-the** [Benjamin-Norton/MCGPT#8]
Might be a bit much, but you could teach a model about the changes between 1.17 and now. 

Only needs to be done once per an openai account.

Would make this much more useful.

Could also tell it what version of MC is being played at the start of each session, if you're not already.

**Comment by Bawnorton** [comment]
I have gone over this before elsewhere and I feel like I'm gonna need to pin this so I don't keep getting asked this as it seems to be a common topic of discussion.

So it can't be done once per account, it has to be done with every conversation via proompting.

Properly fine tuning AI models is incredibly expensive and resource intensive, which is why only big, well funded companies and collectives can do that for models as large as GPT3.

The other way, proompting (providing the model with some initial context that it is missing), is not something I am going to do as I don’t want to provide the model with too much information at the beginning in order to reduce the amount of tokens the mod uses at a base level as it costs money. Thus, providing the necessary information for 1.18+ is not feasible with both goals in mind. I’d also be limiting how much context the model can process as you’re limited to 4096 tokens per request. It’s the reason I cut it off at 10 Chat messages, otherwise each question will cost the end user more and more money per question. It’s 0.002$/token currently and a token is ~4 characters.

Token usage will creep up from the base the more questions you ask as it needs the prior context, thus, keeping the context as short as possible is desirable.

**Comment by adam-the** [comment]
I don't think you've actually read the docs for OpenAI's tuning:
https://platform.openai.com/docs/guides/fine-tuning

Yes it's more expensive, but it's not impossible.

**Comment by Bawnorton** [comment]
I have, you'll notice that isn't available to ChatGPT and is only supported by the instruct models (Babbage, Ada, Curie and Davinci) which are not designed for chat completions.
